"""initial schema

Revision ID: 86cf5526eb74
Revises:
Create Date: 2026-09-26 12:47:04.023667

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86cf5526eb74"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("ring", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="idle", nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recurrence", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("orbit_angle", sa.Float(), nullable=True),
        sa.Column("orbit_radius", sa.Float(), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "recurrence IS NULL OR recurrence IN ('daily', 'weekly', 'monthly')",
            name="tasks_recurrence_values",
        ),
        sa.CheckConstraint("ring IN ('today', 'week', 'someday')", name="tasks_ring_values"),
        sa.CheckConstraint(
            "status IN ('idle', 'in_progress', 'completed', 'archived')", name="tasks_status_values"
        ),
        sa.CheckConstraint("char_length(title) BETWEEN 1 AND 200", name="tasks_title_length"),
        sa.CheckConstraint("priority BETWEEN 0 AND 3", name="tasks_priority_range"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("tasks_user_due_idx", "tasks", ["user_id", "due_at"], unique=False)
    op.create_index("tasks_user_ring_idx", "tasks", ["user_id", "ring"], unique=False)
    op.create_index("tasks_user_status_idx", "tasks", ["user_id", "status"], unique=False)
    op.create_table(
        "task_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("task_events_task_id_idx", "task_events", ["task_id"], unique=False)
    op.create_index(
        "task_events_user_created_idx", "task_events", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("task_events_user_created_idx", table_name="task_events")
    op.drop_index("task_events_task_id_idx", table_name="task_events")
    op.drop_table("task_events")
    op.drop_index("tasks_user_status_idx", table_name="tasks")
    op.drop_index("tasks_user_ring_idx", table_name="tasks")
    op.drop_index("tasks_user_due_idx", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
